version: '3'
 
services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sharefile
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    ports:
      - "5432:5432"


  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1;done;
             sleep 5 &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "db"
  
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A sharefile worker -l info
    volumes:
      - ./app:/app
    
    depends_on:
      - db
      - redis
      - app