# Generated by Django 3.0.3 on 2021-04-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210405_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_f',
            new_name='file_field',
        ),
    ]
