# Generated by Django 3.0.3 on 2021-04-05 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210405_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='add_date',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
        ),
    ]
