# Generated by Django 3.0.3 on 2021-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210405_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='add_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
