# Generated by Django 3.0.3 on 2021-04-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='file_f',
            new_name='file',
        ),
    ]
