# Generated by Django 3.0.3 on 2021-04-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210406_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='home.File'),
        ),
    ]
