# Generated by Django 3.0.3 on 2021-04-07 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20210407_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='given_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
